# A sample Gemfile
source "http://rubygems.org"
gem "jeweler", :group => :development
gem "gemedit", :group => :development
gem "json"
gem "i18n"
gem "trollop"
gem "rest_connection", ">=0.1"
gem "fog", ">=1.0"
gem "highline"
gem "right_popen", "1.0.11"
gem "eventmachine", "0.12.10"
gem "ruby-debug"
gem "colorize"
gem "daemons"
gem "sinatra"
gem "bundler"
gem "cronedit"
gem "algorithms"
gem "less"
gem "rack-ssl"
gem "thin"
gem "rest-client"
gem "ParseTree"
gem "ruby2ruby"
gem "chronic"
gem "elif"
gem "terminal-table"
gem "tzinfo"
gem "google_drive"
gem "system_timer"
gem "mail"
gem 'lockfile'
